#Stored all the IP_address using GITHUB Variables
[master_nodes]
master ansible_host= ${{ vars.MASTER_IP }}ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/key-pair.pem

[worker_nodes]
worker1 ansible_host= ${{ vars.WORKER1_IP }}ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/key-pair.pem
worker2 ansible_host=${{ vars.WORKER1_IP }} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/key-pair.pem
worker3 ansible_host=${{ vars.WORKER1_IP }} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/key-pair.pem

[all:vars]
ansible_python_interpreter=/usr/bin/python3
