[master_nodes]
master ansible_host=18.212.128.68 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/key-pair.pem

[worker_nodes]
worker1 ansible_host=54.237.245.56 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/key-pair.pem
worker2 ansible_host=3.235.100.9 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/key-pair.pem
worker3 ansible_host=54.205.149.98 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/key-pair.pem

[all:vars]
ansible_python_interpreter=/usr/bin/python3
